---
title: "US Tilapia Imports"
author: "Alex Vand"
date: "8/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

```{r}
us_tilapia_imports <- read_csv(here::here("data", "us_tilapia_imports.csv"))

imports_longer <- pivot_longer(data = us_tilapia_imports, col = -country, names_to = "year", values_to = "imports")

imports_longer <- imports_longer %>% 
  mutate(year = as.numeric(year))

yearly_tilapia_tot <- imports_longer %>% 
  dplyr::group_by(year) %>%
  summarize(total_imports = sum(imports, na.rm = TRUE))
```

```{r}
tilapia_plot <- ggplot(data = yearly_tilapia_tot, aes(x = year, y = total_imports)) +
  geom_line()+
  labs(x = "Year",
       y = "Total tilapia imports")

ggsave(here::here("figs", "tilapia_plot.png"), plot = tilapia_plot)
```

```{r}
central_america_imports <- filter(imports_longer, country == c("Ecuador", "Honduras", "Costa Rica", "Mexico"))

central_america_plot <-
  ggplot(data = central_america_imports,
                               aes(x = year,
                                   y = imports)) +
  geom_line(aes(color = country)) +
  labs(title = "Tilapia imports by Central American country",
       x = "Year",
       y = "Tilapia imports") +
  theme_minimal()

ggsave(here::here("figs", "central_america_plot.jpg"), plot = central_america_plot)
```

